/**
 * Tier 1 of the retrieval ladder: the rolling topic digest and the autogenerated
 * glossary. Both are free by construction - pure computation over turns already in
 * memory. No model call, no agent spawn, no I/O. Same turns in, same result out.
 */

import { type GlossaryEntry, TOPIC_DIGEST_CHARS } from "./context-contracts";

type Turn = { role: string; text: string };

/** Determiners a reference may carry that the glossary term does not. */
const DETERMINERS: Record<string, true> = {
	the: true,
	a: true,
	an: true,
	this: true,
	that: true,
	these: true,
	those: true,
	my: true,
	your: true,
	our: true,
	its: true,
	their: true,
	his: true,
	her: true,
};

/** Capitalized words that start sentences everywhere and name nothing. */
const NOT_PROPER_NOUNS: Record<string, true> = Object.fromEntries(
	[
		"about", "add", "after", "also", "and", "answer", "both", "check", "each", "every", "expect",
		"final", "first", "fixed", "found", "from", "here", "into", "just", "keep", "make", "measured",
		"most", "need", "next", "note", "nothing", "only", "open", "other", "plus", "prove", "reply",
		"result", "right", "round", "running", "same", "show", "since", "some", "start", "still", "stop",
		"such", "test", "that", "them", "then", "there", "these", "they", "this", "those", "three",
		"true", "turn", "twice", "two", "under", "until", "use", "used", "user", "very", "watch",
		"were", "what", "when", "where", "which", "while", "with", "yes", "your",
	].map(word => [word, true]),
);

/** Terms too generic to be worth a glossary row. */
const TERM_STOPWORDS: Record<string, true> = {
	true: true,
	false: true,
	null: true,
	yes: true,
	no: true,
	ok: true,
	done: true,
	one: true,
	two: true,
};

/**
 * Strip the markup that hides terms from a plain regex: fenced code, attachment
 * blocks, markdown emphasis, table pipes and escapes. Whitespace is collapsed so
 * a sentence window never spans a wall of blank lines.
 */
export function cleanConversationText(text: string): string {
	return text
		.replace(/```[\s\S]*?```/g, " ")
		.replace(/<attachment>[\s\S]*?<\/attachment>/g, " ")
		.replace(/<\/?attachment>/g, " ")
		.replace(/\[Image #\d+[^\]]*\]/g, " ")
		.replace(/[*_]{1,3}/g, "")
		.replace(/[│┌┐└┘├┤┬┴─╭╮╰╯]/g, " ")
		.replace(/\s+/g, " ")
		.trim();
}

/** The sentence containing `index`, capped at TOPIC_DIGEST_CHARS. */
export function sentenceAround(text: string, index: number): string {
	const boundary = /[.!?;\n]/;
	let start = index;
	while (start > 0 && !boundary.test(text[start - 1] as string)) start--;
	let end = index;
	while (end < text.length && !boundary.test(text[end] as string)) end++;
	const sentence = text.slice(start, Math.min(end + 1, text.length)).trim();
	return capChars(sentence.length > 0 ? sentence : text.slice(index, index + TOPIC_DIGEST_CHARS).trim());
}

/** Hard cap at TOPIC_DIGEST_CHARS, cutting on a word boundary when one is near. */
function capChars(text: string): string {
	if (text.length <= TOPIC_DIGEST_CHARS) return text;
	const clipped = text.slice(0, TOPIC_DIGEST_CHARS);
	const lastSpace = clipped.lastIndexOf(" ");
	return (lastSpace >= TOPIC_DIGEST_CHARS - 40 ? clipped.slice(0, lastSpace) : clipped).trimEnd();
}

/**
 * The current topic in at most TOPIC_DIGEST_CHARS: the latest user turn leads,
 * the running subject of the recent turns fills whatever room is left.
 */
export function buildTopicDigest(turns: readonly Turn[]): string {
	if (turns.length === 0) return "";
	let latestUser = "";
	for (let i = turns.length - 1; i >= 0; i--) {
		const turn = turns[i] as Turn;
		if (turn.role === "user") {
			latestUser = cleanConversationText(turn.text);
			break;
		}
	}
	if (latestUser.length === 0) latestUser = cleanConversationText((turns[turns.length - 1] as Turn).text);

	const head = capChars(latestUser).slice(0, Math.min(TOPIC_DIGEST_CHARS - 24, 168)).trimEnd();
	const subject = runningSubject(turns);
	if (subject.length === 0) return capChars(head);
	return capChars(`${head} | topic: ${subject}`);
}

/** The terms the recent turns keep coming back to, most repeated first. */
function runningSubject(turns: readonly Turn[]): string {
	const recent = turns.slice(Math.max(0, turns.length - 6));
	const counts = new Map<string, number>();
	for (const turn of recent) {
		for (const term of extractTerms(cleanConversationText(turn.text))) {
			counts.set(term.term, (counts.get(term.term) ?? 0) + 1);
		}
	}
	return [...counts.entries()]
		.sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
		.slice(0, 6)
		.map(([term]) => term)
		.join(", ");
}

interface TermHit {
	readonly term: string;
	readonly index: number;
}

/** Term shapes a conversation coins: identifiers, paths, ports, names, phrases. */
const TERM_PATTERNS: readonly RegExp[] = [
	/`([^`\n]{2,60})`/g,
	/"([^"\n]{3,60})"/g,
	/[\u201c]([^\u201d\n]{3,60})[\u201d]/g,
	/((?:~|\.)?\/[A-Za-z0-9._~/-]{3,80})/g,
	/\b([A-Za-z0-9_-]+\.(?:ts|tsx|js|json|jsonl|md|py|yml|yaml|html|txt|sh))\b/g,
	/\b(?:localhost|127\.0\.0\.1):(\d{2,5})\b/g,
	/\bport\s+(\d{2,5})\b/gi,
	/\b([a-z][a-z0-9]*(?:-[a-z0-9]+)+)\b/g,
	/\b([A-Z][a-z]+(?:[A-Z][a-z0-9]+)+)\b/g,
	/\bthe\s+([a-z]+\s+(?:side|mode|neuron|tier|ladder|gate|fork|router|binary|analyzer))\b/gi,
	/\b([A-Za-z][A-Za-z0-9]{2,}\s+(?:mode|neuron|router|gate))\b/g,
];

/** Capitalized word used mid-sentence, i.e. a name rather than a sentence opener. */
const PROPER_NOUN = /(\S)\s+([A-Z][a-z]{3,})\b/g;

function normalizeTerm(raw: string): string {
	return raw
		.replace(/\(\)$/, "")
		.replace(/^[^A-Za-z0-9/~.]+/, "")
		.replace(/[^A-Za-z0-9)\]]+$/, "")
		.replace(/\s+/g, " ")
		.trim();
}

function usableTerm(term: string): boolean {
	if (term.length < 3 || term.length > 60) return false;
	if (TERM_STOPWORDS[term.toLowerCase()] === true) return false;
	if (term.split(" ").length > 6) return false;
	return /[A-Za-z0-9]/.test(term);
}

/** Every term the text establishes, with the offset of its first occurrence. */
function extractTerms(text: string): TermHit[] {
	const first = new Map<string, number>();
	for (const pattern of TERM_PATTERNS) {
		pattern.lastIndex = 0;
		for (let m = pattern.exec(text); m !== null; m = pattern.exec(text)) {
			const term = normalizeTerm(m[1] ?? "");
			if (!usableTerm(term)) continue;
			const key = term.toLowerCase();
			if (!first.has(key)) first.set(key, m.index);
		}
	}
	PROPER_NOUN.lastIndex = 0;
	for (let m = PROPER_NOUN.exec(text); m !== null; m = PROPER_NOUN.exec(text)) {
		const lead = m[1] as string;
		const word = m[2] as string;
		if (/[.!?:]/.test(lead)) continue;
		if (NOT_PROPER_NOUNS[word.toLowerCase()] === true) continue;
		const key = word.toLowerCase();
		if (!first.has(key)) first.set(key, m.index + lead.length + 1);
	}
	return [...first.entries()]
		.map(([term, index]) => ({ term, index }))
		.sort((a, b) => a.index - b.index || (a.term < b.term ? -1 : 1));
}

/** Cap so one long conversation cannot turn the free tier into a linear scan of thousands. */
const MAX_GLOSSARY_ENTRIES = 300;

/**
 * The terms this conversation established, each defined by the turn that
 * introduced it. Deterministic: no model, no ranking by recency of access.
 */
export function buildGlossary(turns: readonly Turn[]): GlossaryEntry[] {
	const introduced = new Map<string, { entry: GlossaryEntry; count: number }>();
	for (let i = 0; i < turns.length; i++) {
		const text = cleanConversationText((turns[i] as Turn).text);
		for (const hit of extractTerms(text)) {
			const existing = introduced.get(hit.term);
			if (existing) {
				introduced.set(hit.term, { entry: existing.entry, count: existing.count + 1 });
				continue;
			}
			introduced.set(hit.term, {
				entry: { term: hit.term, definition: sentenceAround(text, hit.index), turnIndex: i + 1 },
				count: 1,
			});
		}
	}
	return [...introduced.values()]
		.sort((a, b) => b.count - a.count || a.entry.turnIndex - b.entry.turnIndex || (a.entry.term < b.entry.term ? -1 : 1))
		.slice(0, MAX_GLOSSARY_ENTRIES)
		.map(candidate => candidate.entry)
		.sort((a, b) => a.turnIndex - b.turnIndex || (a.term < b.term ? -1 : 1));
}

/** Lowercase, unquote, and drop leading determiners: `the other one` -> `other one`. */
function normalizeLookup(text: string): string {
	const bare = text
		.toLowerCase()
		.replace(/[`"'\u201c\u201d]/g, "")
		.replace(/[^a-z0-9./~:_\- ]+/g, " ")
		.replace(/\s+/g, " ")
		.trim();
	const words = bare.split(" ").filter(word => word.length > 0);
	let start = 0;
	while (start < words.length - 1 && DETERMINERS[words[start] as string] === true) start++;
	return words.slice(start).join(" ");
}

/**
 * Newest glossary entry matching a referring phrase, tolerating the articles a
 * reference carries and the glossary term does not. Null when nothing matches.
 */
export function lookupGlossary(glossary: readonly GlossaryEntry[], referenceText: string): GlossaryEntry | null {
	const needle = normalizeLookup(referenceText);
	if (needle.length < 3) return null;
	let best: GlossaryEntry | null = null;
	let bestScore = 0;
	for (const entry of glossary) {
		const term = normalizeLookup(entry.term);
		if (term.length < 2) continue;
		const score =
			term === needle ? 3 : ` ${needle} `.includes(` ${term} `) ? 2 : ` ${term} `.includes(` ${needle} `) ? 1 : 0;
		if (score === 0) continue;
		if (score > bestScore || (score === bestScore && best !== null && entry.turnIndex >= best.turnIndex)) {
			best = entry;
			bestScore = score;
		}
	}
	return best;
}
